# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"$\n\x0cSumarRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\"\n\rSumarResponse\x12\x11\n\tresultado\x18\x01 \x01(\x05\x32\x34\n\nCalculator\x12&\n\x05Sumar\x12\r.SumarRequest\x1a\x0e.SumarResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMARREQUEST']._serialized_start=20
  _globals['_SUMARREQUEST']._serialized_end=56
  _globals['_SUMARRESPONSE']._serialized_start=58
  _globals['_SUMARRESPONSE']._serialized_end=92
  _globals['_CALCULATOR']._serialized_start=94
  _globals['_CALCULATOR']._serialized_end=146
# @@protoc_insertion_point(module_scope)
